# Generated by Django 3.2.3 on 2021-05-17 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=200, verbose_name='event_name')),
                ('event_description', models.CharField(default='', max_length=2000, verbose_name='event_description')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Created On')),
            ],
        ),
    ]
