# Generated by Django 3.2.3 on 2021-05-19 07:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('description', models.CharField(default='', max_length=2000, verbose_name='description')),
                ('max_capacity', models.PositiveSmallIntegerField(default=0, verbose_name='max_capacity')),
                ('location', models.CharField(default='', max_length=500)),
                ('contact_number', models.PositiveSmallIntegerField(default=0, verbose_name='contact_number')),
                ('alt_contact_number', models.PositiveSmallIntegerField(default=0, verbose_name='alt_contact_number')),
                ('contact_email', models.EmailField(max_length=254)),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Created On')),
                ('created_by', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to=settings.AUTH_USER_MODEL)),
                ('participated_in', models.ManyToManyField(related_name='participated_in', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=200)),
                ('email', models.EmailField(default=None, max_length=254)),
                ('event', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='events.event')),
            ],
        ),
    ]
