# Generated by Django 3.2.3 on 2021-05-19 07:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='participated_in',
        ),
        migrations.AddField(
            model_name='event',
            name='participated_in',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participated_in', to=settings.AUTH_USER_MODEL),
        ),
    ]
