# Generated by Django 3.2.3 on 2021-05-19 08:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0002_auto_20210519_1326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='participated_in',
        ),
        migrations.AddField(
            model_name='event',
            name='participated_in',
            field=models.ManyToManyField(related_name='participated_in', to=settings.AUTH_USER_MODEL),
        ),
    ]
