# Generated by Django 3.2.3 on 2021-05-19 11:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20210519_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 19, 11, 8, 57, 60655, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='event',
            name='last_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 19, 11, 8, 57, 60655, tzinfo=utc)),
        ),
    ]
