# Generated by Django 3.2.3 on 2021-05-23 14:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_auto_20210523_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 23, 14, 11, 15, 476077, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_image',
            field=models.ImageField(blank=True, default='events/event_default.jpg', upload_to='events/83566852-b704-4cbe-90e3-6ccf8cf5f499'),
        ),
        migrations.AlterField(
            model_name='event',
            name='last_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 23, 14, 11, 15, 476077, tzinfo=utc)),
        ),
    ]
